export const SETTINGS_DEFAULT_VALUES: Record<string, string> = {
  AF: 'Afrikaans',
  AL: 'Albanian',
  AR: 'Arabic',
  AZ: 'Azerbaijani',
  BG: 'Bulgarian',
  CA: 'Catalan',
  CZ: 'Czech',
  DA: 'Danish',
  DE: 'German',
  EL: 'Greek',
  EN: 'English',
  EU: 'Basque',
  FA: 'Persian (Farsi)',
  FI: 'Finnish',
  FR: 'French',
  GL: 'Galician',
  HE: 'Hebrew',
  HI: 'Hindi',
  HR: 'Croatian',
  HU: 'Hungarian',
  ID: 'Indonesian',
  IT: 'Italian',
  JA: 'Japanese',
  KR: 'Korean',
  LA: 'Latvian',
  LT: 'Lithuanian',
  MK: 'Macedonian',
  NO: 'Norwegian',
  NL: 'Dutch',
  PL: 'Polish',
  PT: 'Portuguese',
  PT_BR: 'Português Brasil',
  RO: 'Romanian',
  RU: 'Russian',
  SE: 'Swedish',
  SK: 'Slovak',
  SL: 'Slovenian',
  SP: 'Spanish',
  ES: 'Spanish',
  SR: 'Serbian',
  TH: 'Thai',
  TR: 'Turkish',
  UK: 'Ukrainian',
  VI: 'Vietnamese',
  ZH_CN: 'Chinese Simplified',
  ZH_TW: 'Chinese Traditional',
  ZU: 'Zulu',
};

